import type { Metadata } from 'next'
import cx from 'classnames'
import 'rc-slider/assets/index.css'
import '@/styles/globals.css'
import { inter } from './fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cx(inter.className)}>{children}</body>
		</html>
	)
}
